name: ItemMods
author: CodeDoctorDE
version: "1.4"
load: STARTUP
api-version: "1.14"
main: com.github.codedoctorde.itemmods.ItemMods
commands:
  itemmods:
    aliases:
      - itemmods
      - itemmod
      - itemm
      - imods
      - imod
      - im
      - ims
    usage: "\u00a74Usage: \u00a73/itemmods\u00a74!"
  giveitem:
    aliases:
      - givecustomitem
      - giveitemmodsitem
      - giveitemmoditem
      - giveimitem
      - giveitemmitem
      - giveimoditem
      - giveimodsitem
      - givemoditem
    permission: itemmods.admin
    usage: "\u00a74Usage: \u00a73/givecustomitem <Player> <Item> [<Amount>]\u00a74!"
softdepend:
  - BetterGUI
