name: itemmods
author: CodeDoctorDE
version: 1.0
api-version: "1.14"
main: com.gitlab.vangora.itemmods.main.Main
commands:
  itemmods:
    aliases:
      - itemmods
      - itemmod
      - itemm
      - imods
      - imod
      - im
      - ims
    usage: "\u00a74Usage: \u00a73/itemmods\u00a74!"
