name: Mirror to Gitea Repo

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:CodeDoctorDE/ItemMods.git'
          destination-repo: 'git@git.codedoctor.tk:ItemMods/Plugin.git'